#!/usr/bin/env python3
"""Restore the split Round96 source package.

The split binary parts are intentionally not generated by this script. The
operator must upload the two part files and manifest into this directory first.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import zipfile
from pathlib import Path

PACKAGE_STEM = "eve_v3_round96_runtime_mapping_enable_smoke_precheck.zip"
PART_CANDIDATES = (
    (f"{PACKAGE_STEM}.part01", "part01"),
    (f"{PACKAGE_STEM}.part02", "part02"),
)
MANIFEST_CANDIDATES = ("eve_v3_round96_split_manifest.json", "manifest")
EXTRACT_DIR = "round96_source"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_expected_sha256(manifest_path: Path) -> str:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    expected = manifest.get("source_sha256")
    if not isinstance(expected, str) or not expected:
        raise ValueError(f"{manifest_path.name} must contain a non-empty source_sha256 string")
    return expected.lower()


def first_existing(package_dir: Path, candidates: tuple[str, ...]) -> Path | None:
    for name in candidates:
        path = package_dir / name
        if path.exists():
            return path
    return None


def require_inputs(package_dir: Path) -> tuple[list[Path], Path]:
    part_paths: list[Path] = []
    missing_groups: list[str] = []
    for candidates in PART_CANDIDATES:
        path = first_existing(package_dir, candidates)
        if path is None:
            missing_groups.append(" or ".join(candidates))
        else:
            part_paths.append(path)

    manifest_path = first_existing(package_dir, MANIFEST_CANDIDATES)
    if manifest_path is None:
        missing_groups.append(" or ".join(MANIFEST_CANDIDATES))

    if missing_groups:
        missing_list = "\n".join(f"- {name}" for name in missing_groups)
        raise FileNotFoundError(
            "Round96 split package inputs are missing:\n"
            f"{missing_list}\n\n"
            "Upload them into eve_v3_autonomous_handoff/packages/ and rerun this script."
        )
    return part_paths, manifest_path


def restore_zip(part_paths: list[Path], output_path: Path) -> None:
    with output_path.open("wb") as output:
        for part_path in part_paths:
            with part_path.open("rb") as part:
                shutil.copyfileobj(part, output, length=1024 * 1024)


def extract_zip(zip_path: Path, extract_dir: Path) -> None:
    with zipfile.ZipFile(zip_path) as archive:
        bad_member = archive.testzip()
        if bad_member is not None:
            raise zipfile.BadZipFile(f"Corrupt zip member detected: {bad_member}")
        extract_dir.mkdir(parents=True, exist_ok=True)
        archive.extractall(extract_dir)


def main() -> int:
    parser = argparse.ArgumentParser(description="Restore and verify the Round96 split source package.")
    parser.add_argument(
        "--verify-only",
        action="store_true",
        help="Verify the restored zip SHA-256 but do not extract it.",
    )
    args = parser.parse_args()

    package_dir = Path(__file__).resolve().parent
    zip_path = package_dir / PACKAGE_STEM
    extract_dir = package_dir / EXTRACT_DIR

    try:
        part_paths, manifest_path = require_inputs(package_dir)
        print("Using split package inputs:")
        for part_path in part_paths:
            print(f"- {part_path.name}")
        print(f"- {manifest_path.name}")
        restore_zip(part_paths, zip_path)
        expected_sha256 = load_expected_sha256(manifest_path)
        actual_sha256 = sha256_file(zip_path)
        if actual_sha256 != expected_sha256:
            raise ValueError(
                "Restored zip SHA-256 mismatch:\n"
                f"expected: {expected_sha256}\n"
                f"actual:   {actual_sha256}"
            )
        print(f"SHA-256 verified: {actual_sha256}")
        if args.verify_only:
            return 0
        extract_zip(zip_path, extract_dir)
        print(f"Extracted Round96 source to: {extract_dir}")
        return 0
    except Exception as exc:  # noqa: BLE001 - CLI should report any restore blocker clearly.
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
